# Generated by Django 5.2.7 on 2025-10-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_picture_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
